### ISSUE TITLE
Composition API

### ISSUE THREAD

**Issue by bmulholland** [codedbychavez/configcat-vue#15]
Sometimes I need to check values in JS instead of HTML. In that case, using the composition API would be nice. Here's some code I wrote for my own version of a responsive value, maybe something like this could work?

```
    isEnabled(key, defaultValue, options) {
      const returnValue = ref(defaultValue)

      if (!configCatClient) return returnValue

      configCatClient
        .getValueAsync(key, false, options.user)
        .then((value) => {
          returnValue.value = value
        })
        .catch((error) => {
          captureException(error)
        })

      return returnValue
    },
```

**Comment by codedbychavez** [comment]
Hi @bmulholland Thank you so much for raising this. I'll have a look and keep you posted here.

**Comment by codedbychavez** [comment]
Hey @bmulholland, sorry for my late reply. Here's a link to what you may need: https://configcat.com/docs/sdk-reference/community/vue/#using-the-underlying-configcat-client
