### ISSUE TITLE
Excess divs mess with styling

### ISSUE THREAD

**Issue by bmulholland** [codedbychavez/configcat-vue#21]
The component adds extra divs, which use default styling and make it hard to style things. For example, if I need everything to have 100% width, I can't do that, because the component has https://github.com/codedbychavez/configcat-vue/blob/main/src/components/FeatureWrapper.vue#L3. 

There's probably a few options for how to approach an alternative, happy to pair on it if you need

**Comment by bmulholland** [comment]
I forked the component and changed the template to this, which worked perfectly:
```
  <slot v-if="isFeatureFlagEnabled === true" />
  <slot v-else-if="isFeatureFlagEnabled === false" name="else" />
  <slot v-else name="loading" />
```

**Comment by adams85** [comment]
Seems like a reasonable change to me. What do you think, @codedbychavez?

BTW, @bmulholland, feel free to submit your suggestions in the form of pull requests.

**Comment by codedbychavez** [comment]
hmmm 🤔 , it makes sense. I can include in a next pull request. Thanks for raising this @bmulholland, much appreciated.

**Comment by codedbychavez** [comment]
Hi @bmulholland, thanks for your patience. I've created a PR to address this issue: <https://github.com/codedbychavez/configcat-vue/pull/22>
