### ISSUE TITLE
Not refreshing the flag

### ISSUE THREAD

**Issue by aleixmorgadas** [codedbychavez/configcat-vue#3]
Thank you for making this library! It really helped us setting up the configcat in our Vue application :heart: 

I have noticed tho that it is not refreshing the flag without refreshing the page.

**Comment by codedbychavez** [comment]
Hi @aleixmorgadas fixed and merged into main (https://github.com/codedbychavez/configcat-vue/pull/5). Will publish a new version to npm after some internal testing. Stay tuned.
